---
# Secret pour PostgreSQL dans le namespace devops
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  # IMPORTANT: Changez ces valeurs en production !
  # Pour encoder en base64: echo -n 'votre-valeur' | base64
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_secure_password_2024"
  POSTGRES_DB: "sonarqube"


