---
# StorageClass pour le stockage local (développement/test)
# En production, utilisez un StorageClass avec provisionnement dynamique (NFS, Ceph, etc.)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain


