---
apiVersion: v1
kind: Namespace
metadata:
  name: devops
  labels:
    name: devops
    environment: infrastructure
    managed-by: kubernetes
  annotations:
    description: "Namespace pour les outils DevOps (Jenkins, Nexus, SonarQube, etc.)"
---
# ResourceQuota pour limiter les ressources dans le namespace devops
apiVersion: v1
kind: ResourceQuota
metadata:
  name: devops-quota
  namespace: devops
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "20"
    services.loadbalancers: "0"
    services.nodeports: "0"
---
# LimitRange pour définir les limites par défaut des pods
apiVersion: v1
kind: LimitRange
metadata:
  name: devops-limit-range
  namespace: devops
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
  - max:
      cpu: "8"
      memory: 16Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod

